### ISSUE TITLE
I2S clock not correct which may cause sample-rate issues

### ISSUE THREAD

**Issue by jpiat** [nejohnson2/rpi-i2s#3]
Hi,

i measured the i2s clock for the 32bit@48kHz capture and i get 4.8MHz (100x fs) instead of 3.072 (64x fs) as expected by the microphone. This is higher than max clock frequency of the microphone 3.379 and should not work or give bad audio data. Any idea on how to change i2s configuration to get correct clock speed ?

**Comment by nejohnson2** [comment]
What microphone are you using?  I believe the ICS4342 (and ICS43434) are 24bit, which may be the issue.

**Comment by jpiat** [comment]
The clock line is driven by the raspberry pi not the microphone. With a
4.8MHz clock the microphone should not work well. Do you have any way to
measure the frequency of the clock line on your side ?
Jonathan Piat

Le 15 déc. 2017 7:18 PM, "Nicholas Johnson" <notifications@github.com> a
écrit :

**Comment by jpiat** [comment]
The solution is to recompile the simple-card module (snd-soc-simple-card.ko) as stated in this thread https://www.raspberrypi.org/forums/viewtopic.php?t=91237&start=50
otherwise the bclk (i2s clock) is 100x the sample-rate (4.8Mhz for 48kHz) instead of 64x. This may not cause issues but 4.8MHz is out of maximum spec for this microphone (3.37MHz max).
