### ISSUE TITLE
No rule to make target 'modules'

### ISSUE THREAD

**Issue by DotNetAge** [nejohnson2/rpi-i2s#7]
All steps i have done successful expect compile the rpi-i2s-audio, i always gets 'No rule to make target modules' , could you help me to resolve this problem ?

```
pi@raspberrypi:~/rpi-i2s-audio $ make -C /lib/modules/$(uname -r )/build M=$(pwd) modules
make: Entering directory '/lib/modules/4.14.69+/build'
make: *** No rule to make target 'modules'.  Stop.
make: Leaving directory '/lib/modules/4.14.69+/build'
``

**Comment by nejohnson2** [comment]
Make sure you're running the command within the 'rpi-i2s-audio' directory.  If it still isnt working, you've most likely not compiled the kernel properly.  The ```make``` command is not finding what it needs in the directory '/lib/modules/4.14.69+/build' to compile the i2s module.
